import { setNetworkId } from '@midnight-ntwrk/midnight-js-network-id';
import path from 'node:path';

// 1. Resolve the current directory
export const currentDir = path.resolve(new URL(import.meta.url).pathname, '..');

// 2. Define Contract Assets Location
// This points to the compiled contract files generated by 'npm run build'
export const contractConfig = {
  privateStateStoreName: 'counter-private-state',
  zkConfigPath: path.resolve(currentDir, '..', '..', 'vet-contract', 'src', 'managed', 'counter'),
};

// 3. Define the Config Interface
export interface Config {
  readonly logDir: string;
  readonly indexer: string;
  readonly indexerWS: string;
  readonly node: string;
  readonly proofServer: string;
}

// 4. LOCAL NETWORK CONFIG (The Fix)
// We use 127.0.0.1 to force IPv4 and avoid Node.js/Docker address confusion.
export class UndeployedConfig implements Config {
  logDir = path.resolve(currentDir, '..', 'logs', 'tui-standalone', `${new Date().toISOString()}.log`);
  
  indexer = 'http://127.0.0.1:8088/api/v3/graphql';
  indexerWS = 'ws://127.0.0.1:8088/api/v3/graphql/ws';
  node = 'http://127.0.0.1:9944';
  proofServer = 'http://127.0.0.1:6300';

  constructor() {
    setNetworkId('undeployed');
  }
}

// 5. TESTNET CONFIG (Preview)
export class PreviewConfig implements Config {
  logDir = path.resolve(currentDir, '..', 'logs', 'tui-preview', `${new Date().toISOString()}.log`);
  
  indexer = 'https://indexer.preview.midnight.network/api/v3/graphql';
  indexerWS = 'wss://indexer.preview.midnight.network/api/v3/graphql/ws';
  node = 'https://rpc.preview.midnight.network';
  proofServer = 'http://127.0.0.1:6300';

  constructor() {
    setNetworkId('preview');
  }
}

// 6. DEVNET CONFIG (Preprod)
export class PreprodConfig implements Config {
  logDir = path.resolve(currentDir, '..', 'logs', 'tui-preprod', `${new Date().toISOString()}.log`);
  
  indexer = 'https://indexer.preprod.midnight.network/api/v3/graphql';
  indexerWS = 'wss://indexer.preprod.midnight.network/api/v3/graphql/ws';
  node = 'https://rpc.preprod.midnight.network';
  proofServer = 'http://127.0.0.1:6300';

  constructor() {
    setNetworkId('preprod');
  }
}